name: Patch upstream release
run-name: Apply patches to release ${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify an upstream version tag'
        required: true
        default: 'v1.23.1'
      suffix:
        description: 'Optional image tag suffix'
        default: ''
        required: false

jobs:
  patch-upstream:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Move patches
        run: mv patches /tmp/patches

      - name: Add upstream and fetch tags
        run: |
          git remote add upstream https://github.com/go-gitea/gitea.git
          git fetch upstream --tags

      - name: Verify upstream tag exists
        run: |
          if ! git rev-parse "refs/tags/${{ inputs.tag }}" >/dev/null 2>&1; then
            echo "Error: Tag ${{ inputs.tag }} does not exist upstream."
            exit 1
          fi

      - name: Create branch from determined tag
        run: git checkout tags/${{ inputs.tag }} -b apply-patches-${{ inputs.tag }}${{ inputs.suffix }}

      - name: Configure Git user
        run: |
          git config --global user.name 'Bart van der Braak'
          git config --global user.email 'bartvdbraak@users.noreply.github.com'

      - name: Apply patches
        run: |
          if ! git am --3way /tmp/patches/*.patch; then
            echo "Patch application failed."
            git am --abort
            exit 1
          fi

      - name: Clean tags and push new
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git tag -d "${{ inputs.tag }}${{ inputs.suffix }}" || echo "Local tag does not exist, skipping delete."
          git push --delete origin "${{ inputs.tag }}${{ inputs.suffix }}" || echo "Remote tag does not exist, skipping delete."
          git tag -a "${{ inputs.tag }}${{ inputs.suffix }}" -m "Tagging version ${{ inputs.tag }} after applying patches"
          git push origin "${{ inputs.tag }}${{ inputs.suffix }}" --force
          echo '{"ref":"${{ inputs.tag }}${{ inputs.suffix }}"}' | gh workflow run build.yml --ref "${{ github.ref_name }}"	--repo "blender/gitea" --json

      - name: Push branch
        if: always()
        run: git push origin apply-patches-${{ inputs.tag }}${{ inputs.suffix }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

